package org.aksw.commons.collections.generator;

/**
 * Generator which allows giving ids back for re-use.
 * Implementations may or may not validate whether given back items
 * have actually previously been generated by this generator.
 * 
 * @author raven
 *
 * @param <T>
 */
public interface GeneratorLending<T> 
	extends Generator<T>
{
	boolean giveBack(T item);
}
